-- Create database and schema for real-time transaction monitoring
CREATE DATABASE IF NOT EXISTS FRAUD_DETECTION_DB;
USE DATABASE FRAUD_DETECTION_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;
USE SCHEMA ANALYTICS;

-- Table schema for flagged high-risk transactions
CREATE OR REPLACE TABLE FLAG_TRANSACTIONS (
    TRANSACTION_ID STRING,
    USER_ID STRING,
    TRANSACTION_AMOUNT FLOAT,
    RISK_SCORE FLOAT,
    IS_FRAUDULENT BOOLEAN,
    DETECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Analytical query to aggregate high-risk fraud alerts by user
SELECT 
    USER_ID,
    COUNT(TRANSACTION_ID) AS total_flagged_txns,
    AVG(RISK_SCORE) AS avg_risk_score
FROM FLAG_TRANSACTIONS
WHERE IS_FRAUDULENT = TRUE
GROUP BY USER_ID
HAVING COUNT(TRANSACTION_ID) > 1;
